### ISSUE TITLE
It doesn't compile with the newest kade.

### ISSUE THREAD

**Issue by DoomEternal** [TorchTheDragon/FNFTorchEdition#1]
When compiling the game on the newest kade engine it just doesn't want to work. I compiled it on the earlier version and it worked just fine. I removed the two lines of code and then it was able to compile- but when I loaded a song the character selection would compress all the characters together,
![Screenshot 2021-08-01 034858](https://user-images.githubusercontent.com/85465645/127768688-0e456915-57fa-42d1-bf36-d948bb1cea7b.png)
![Screenshot 2021-08-01 041121](https://user-images.githubusercontent.com/85465645/127768689-d1ba9757-30b3-48cb-8a0c-f3ab40e92542.png)

**Comment by TorchTheDragon** [comment]
Firstly, I don't know if this'll work on the new ones cuz mine is on 1.5.4.
Secondly, in my notes (They are inside the source folder) I added an **IMPORTANT** section to help explain what I forgot to mention. It solves the issues of the variables "sprTracker" and "hasPlayedOnce"

**Comment by DoomEternal** [comment]
I saw your updated comment and it worked! It still works with the newest one :))
