### ISSUE TITLE
offsets issue

### ISSUE THREAD

**Issue by 7oltan** [TorchTheDragon/FNFTorchEdition#2]
when i finshed everything in the vid i compaild the game it worked but the offsets r fucked so can someone help me with it

this is a picture
![Screenshot 2021-09-17 184731](https://user-images.githubusercontent.com/87986834/133817052-32307751-3496-46c6-ac44-f7c5bd7b24f2.png)

**Comment by TorchTheDragon** [comment]
There was a link in the description of the video, as well as in the pinned comment, that was labeled as **IMPORTANT** so it could fix this issue. Just follow the instructions on this page (https://github.com/TorchTheDragon/FNFTorchEdition/blob/main/notes/NotesTakenDuringCreation.txt) that are under the IMPORTANT section.

**Comment by TorchTheDragon** [comment]
#1 This was also covered in this closed issue.
